### ISSUE TITLE
how to start it

### ISSUE THREAD

**Issue by arisobel** [isman7/Dashboardpy#1]
Please explain better how to run server with what already have.

**Comment by sla-te** [comment]
After doing `python -m pip install configparser` in addition to the readme and editing the code to import configparser instead of ConfigParser, then installing his dashboard by `python -m pip install git+git://github.com/isman7/Dashboardpy` and editing the import to `from dashboard.main import Dashboard, bottle` inside the example and also inside the Dashboard package itself, I got it to start up by doing `bottle_main_thread().run()` the server but now I get: `Template 'menu' not found.`

**Comment by isman7** [comment]
Woa, this is a really old project and unmaintained. Let me check it during the weekend and I will check any details that could be missing. 

Cheers,

**Comment by sla-te** [comment]
Hey, thanks for the response. Yeah I'm trying to get into creating a GUI with cefpython, this one would be a good place to start. If you have something more up to date im down :)

**Comment by isman7** [comment]
There you go, now there is a new branch with the code running an a very brief update in the instructions. However, as I said, it is really a non-maintained code...

I the code works also for you I will merge it.

**Comment by sla-te** [comment]
It works, thank you :)
